# Generated by Django 5.2 on 2025-05-23 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lesson_options_alter_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hearts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_heart_refill',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course'),
        ),
        migrations.CreateModel(
            name='MatchingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('column_a', models.JSONField()),
                ('column_b', models.JSONField()),
                ('correct_pairs', models.JSONField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_questions', to='core.lesson')),
            ],
        ),
    ]
